USE [StockReporting]
GO

/****** Object:  Table [dbo].[StocksUSA]    Script Date: 10/8/2024 3:05:53 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[StocksUSARowBased]') AND type in (N'U'))
DROP TABLE [dbo].[StocksUSARowBased]
GO

CREATE TABLE [dbo].[StocksUSARowBased] (
[ID] int NOT NULL IDENTITY(1,1) PRIMARY KEY,
[Description] varchar(50),
[Symbol] varchar(50),
[EX] varchar(50),
[DATE] date,
[DAYOFWEEK] varchar(50),
[Market CapnNEW] varchar(50),
[%Change] Decimal(18,4),
[% In The Money] Decimal(18,4),
[% Out Of The Money] Decimal(18,4),
[52High]Decimal(18,4),
[52Low] Decimal(18,4),
[ADX] Decimal(18,4),
[ADXBreakoutsFilter] Decimal(18,4),
[ADXCrossover] Decimal(18,4),
[ADXR] Decimal(18,4),
[AM_Detector] Decimal(18,4),
[APTR] Decimal(18,4),
[ARSI] Decimal(18,4),
[ATR] Decimal(18,4),
[ATRHighSMABreakoutsFilter] Decimal(18,4),
[ATRTrailingStop] Decimal(18,4),
[AbandonedBaby] Decimal(18,4),
[AccDist] Decimal(18,4),
[AccelerationBands] Decimal(18,4),
[AccelerationDecelerationOsc] Decimal(18,4),
[AccumDistBuyPr] Decimal(18,4),
[AccumDistPrVol] Decimal(18,4),
[AccumulationDistribution] Decimal(18,4),
[AccumulationSwingIndex] Decimal(18,4),
[AdaptiveEMA] Decimal(18,4),
[AdvanceBlock] Decimal(18,4),
[AdvanceDecline] Decimal(18,4),
[AdvanceDeclineCumulativeAvg] Decimal(18,4),
[Alpha2] Decimal(18,4),
[AlphaJensen] Decimal(18,4),
[AnchoredVWAP] Decimal(18,4),
[AroonIndicator] Decimal(18,4),
[AroonOscillator] Decimal(18,4),
[Ask] Decimal(18,4),
[AS] Decimal(18,4),
[AX] varchar(1),
[Avg Price] Decimal(18,4),
[Avg_Vol_YTD] Decimal(18,4),
[AwesomeOscillator] Decimal(18,4),
[BBDivergence] Decimal(18,4),
[Back Expected Move] varchar(50),
[Back Vol] Decimal(18,4),
[BalanceOfMarketPower] Decimal(18,4),
[BandpassFilter] Decimal(18,4),
[BeltHold] Decimal(18,4),
[Beta] Decimal(18,4),
[Beta1] Decimal(18,4),
[Beta2] Decimal(18,4),
[Bid] Decimal(18,4),
[BS] Decimal(18,4),
[BX] varchar(50),
[BollingerBands] Decimal(18,4),
[BollingerBandsCrossover] Decimal(18,4),
[BollingerBandwidth] Decimal(18,4),
[BollingerPercentB] Decimal(18,4),
[Book Value Per Share - Current (LTM)] Decimal(18,4),
[Book Value Per Share Growth - Current] Decimal(18,4),
[Breakaway] Decimal(18,4),
[CAM_Indicator] Decimal(18,4),
[CCI] Decimal(18,4),
[CCIAverage] Decimal(18,4),
[CPMO] Decimal(18,4),
[CSI] Decimal(18,4),
[Call Sizzle Index] Decimal(18,4),
[CamarillaPoints] Decimal(18,4),
[Cash Flow Per Share - Current (LTM)] Decimal(18,4),
[ChaikinMoneyFlow] Decimal(18,4),
[ChaikinOsc] Decimal(18,4),
[ChaikinOscillator] Decimal(18,4),
[ChaikinVolatility] Decimal(18,4),
[ChandeMomentumOscillator] Decimal(18,4),
[Chg_Open] Decimal(18,4),
[CloseLocationValue] Decimal(18,4),
[Company Address - City] varchar(50),
[Company Address - Nation] varchar(50),
[Company Address - State] varchar(50),
[Company Address - Street] varchar(max),
[Company Address - Zip] varchar(50),
[Company Name] varchar(200),
[Company Phone] varchar(50),
[Company Website] varchar(100),
[ConcealingBabySwallow] Decimal(18,4),
[CondensedCandles] Decimal(18,4),
[CongAdaptiveMovingAverage] Decimal(18,4),
[Correlation] Decimal(18,4),
[CorrelationCycleAngle] Decimal(18,4),
[CorrelationCycleIndicator] Decimal(18,4),
[CorrelationCycleMarketState] Decimal(18,4),
[CorrelationTrendIndicator] Decimal(18,4),
[Cost] Decimal(18,4),
[Cov Return] Decimal(18,4),
[CumulativeOvernightVolume] Decimal(18,4),
[CumulativeVolumeIndex] Decimal(18,4),
[Current Ratio - Current (LTM)] Decimal(18,4),
[Cusip] varchar(50),
"Custom 1" Decimal(18,4),
"Custom 2" Decimal(18,4),
"Custom 3" Decimal(18,4),
"Custom 4" Decimal(18,4),
"Custom 5" Decimal(18,4),
"Custom 6" Decimal(18,4),
"Custom 7" Decimal(18,4),
"Custom 8" Decimal(18,4),
"Custom 9" Decimal(18,4),
"Custom10" Decimal(18,4),
"Custom11" Decimal(18,4),
"Custom12" Decimal(18,4),
"Custom13" Decimal(18,4),
"Custom14" Decimal(18,4),
"Custom15" Decimal(18,4),
"Custom16" Decimal(18,4),
"Custom17" Decimal(18,4),
"Custom18" Decimal(18,4),
"Custom19" Decimal(18,4),
[CyberCyclesOscillator] Decimal(18,4),
[CycleTrendAnalytics] Decimal(18,4),
[DEMA] Decimal(18,4),
[DIMinus] Decimal(18,4),
[DIPlus] Decimal(18,4),
[DMA] Decimal(18,4),
[DMH] Decimal(18,4),
[DMI] Decimal(18,4),
[DMI_Oscillator] Decimal(18,4),
[DMI_ReversalAlerts] Decimal(18,4),
[DMI_StochasticExtreme] Decimal(18,4),
[DailyHighLow] Decimal(18,4),
[DailyOpen] Decimal(18,4),
[DailyRelativeRange] varchar(50),
[DailySMA] Decimal(18,4),
[DarkCloudCover] Decimal(18,4),
[DarvasBox] Decimal(18,4),
[Date of Incorporation] date,
[Days] Decimal(18,4),
[Deliberation] Decimal(18,4),
[Delta] Decimal(18,4),
[DemandIndex] Decimal(18,4),
[DetrendedPriceOsc] Decimal(18,4),
[DeviationScaledMovAvg] Decimal(18,4),
[DeviationScaledOscillator] Decimal(18,4),
[DisparityIndex] Decimal(18,4),
[DisplacedEMA] Decimal(18,4),
[Displacer] Decimal(18,4),
[Div] Decimal(18,4),
[Div.Freq] varchar(50),
[Div. Payout (% of Earnings) - Current (LTM)] Decimal(18,4),
[Div. Payout Per Share (% of EPS) - Current] Decimal(18,4),
[Div. Per Share - Current] Decimal(18,4),
[Div. Per Share - TTM - Current (LTM)] Decimal(18,4),
[Div. Yield - Current] Decimal(18,4),
[Doji] integer,
[Dollar_Volume] Decimal(18,4),
[DoubleSmoothedStochastic] Decimal(18,4),
[DownsideGapThreeMethods] Decimal(18,4),
[DownsideTasukiGap] Decimal(18,4),
[DynamicMomentumIndex] Decimal(18,4),
[EBITDA - Current] Decimal(18,4),
[EPR Lower] Decimal(18,4),
[EPR Upper] Decimal(18,4),
[EPS] Decimal(18,4),
[ESDBands] Decimal(18,4),
[Earnings Per Share - Current] Decimal(18,4),
[Earnings Per Share - TTM - Current (LTM)] Decimal(18,4),
[EaseOfMovement] Decimal(18,4),
[EfficiencyRatio] Decimal(18,4),
[EhlersAutocorrelation] Decimal(18,4),
[EhlersAutocorrelationPeriodogram] Decimal(18,4),
[EhlersDecyclerOscillator] Decimal(18,4),
[EhlersDistantCoefficientFilter] Decimal(18,4),
[EhlersHighpassFilter] Decimal(18,4),
[EhlersRoofingFilter] Decimal(18,4),
[EhlersSimpleDecycler] Decimal(18,4),
[EhlersStochastic] Decimal(18,4),
[EhlersSuperSmootherFilter] Decimal(18,4),
[ElegantOscillator] Decimal(18,4),
[ElliotOscillator] Decimal(18,4),
[Engulfing] integer,
[ErgodicOsc] Decimal(18,4),
[Ermanometry] integer,
[EveningDojiStar] integer,
[EveningStar] integer,
[Ex Div.Date] date,
[Expected Move Diff] varchar(50),
[ExponentialDeviationBands] Decimal(18,4),
[Extrinsic] Decimal(18,4),
[FIR_FiltersOfPriceChange] Decimal(18,4),
[FIR_Hamming] Decimal(18,4),
[FIR_Hann] Decimal(18,4),
[FIR_TriangleWeighting] Decimal(18,4),
[FM_Demodulator] Decimal(18,4),
[FM_Demodulator2] Decimal(18,4),
[FW_CCI_Advanced] Decimal(18,4),
[FW_CCI_Basic] Decimal(18,4),
[FW_DPO_MOBO] Decimal(18,4),
[FW_FisherTransformer] Decimal(18,4),
[FW_MMG] Decimal(18,4),
[FW_MOBO_Advanced] Decimal(18,4),
[FW_MOBO_Basic] Decimal(18,4),
[FW_SOAP] Decimal(18,4),
[FallingThreeMethods] Decimal(18,4),
[FastBeta] Decimal(18,4),
[Fifty_SMA_pct_Change] Decimal(18,4),
[Financial Leverage (Assets/Equity) - Current (LTM)] Decimal(18,4),
[FisherTransform] Decimal(18,4),
[Five_Day_Chg] Decimal(18,4),
[Fixed Charge Coverage Ratio - Current (LTM)] Decimal(18,4),
[ForceIndex] Decimal(18,4),
[ForecastOscillator] Decimal(18,4),
[FourPercentModel] Decimal(18,4),
[FourierSeriesIndicator] Decimal(18,4),
[Free Cash Flow Per Share - Current (LTM)] Decimal(18,4),
[FreedomOfMovement] Decimal(18,4),
[Front Expected Move] varchar(50),
[Front Vol] Decimal(18,4),
[Gamma] Decimal(18,4),
[GapMomentum] Decimal(18,4),
[GatorOscillator] Decimal(18,4),
[Gross Profit Margin - Current (LTM)] Decimal(18,4),
[HACOLT] Decimal(18,4),
[HHLLS] Decimal(18,4),
[HLVolatility] Decimal(18,4),
[HTB/ETB] varchar(3),
[HV_Percentile] Decimal(18,4),
[Hammer] integer,
[HangingMan] integer,
[Harami] integer,
[HaramiCross] integer,
[HeikinAshiDiff] Decimal(18,4),
[HiLoActivator] Decimal(18,4),
[High] Decimal(18,4),
[High/Low Graph] Decimal(18,4),
[HighPriceGappingPlay] integer,
[HistoricalVolatility] Decimal(18,4),
[HomingPigeon] integer,
[HullMovingAvg] Decimal(18,4),
[IFT_StochOsc] Decimal(18,4),
[IV_Percentile] Decimal(18,4),
[Ichimoku] Decimal(18,4),
[IdenticalThreeCrows] integer,
[ImpVolatility] Decimal(18,4),
[Impl Vol] Decimal(18,4),
[Impulse] integer,
[InNeck] integer,
[Industry] varchar(200),
[Inertia] Decimal(18,4),
[Initial Margin] varchar(50),
[Interest Rate - Estimated Average - Current (LTM)] Decimal(18,4),
[IntradayFlagFormation] integer,
[IntradayMomentumIndex] Decimal(18,4),
[Intrinsic] varchar(100),
[Inventory Turnover - Current (LTM)] Decimal(18,4),
[InvertedHammer] integer,
[KeltnerChannels] Decimal(18,4),
[Kicking] integer,
[KlingerHistogram] Decimal(18,4),
[KlingerOscillator] Decimal(18,4),
[LBR_PaintBars] integer,
[LBR_SmartADX] Decimal(18,4),
[LBR_ThreeTenOscillator] Decimal(18,4),
[Last] Decimal(18,4),
[Last Annual Filing Date] date,
[Last Interim Filing Date] date,
[Last Size] Decimal(18,4),
--[Last] Decimal(18,4),
[LX] varchar(50),
[LeavittConvolution] Decimal(18,4),
[LeavittConvolutionAcceleration] Decimal(18,4),
[LeavittConvolutionSlope] Decimal(18,4),
[LegacyEMA] Decimal(18,4),
[LinearRegAdjEMA] Decimal(18,4),
[LinearRegCh100] Decimal(18,4),
[LinearRegCh50] Decimal(18,4),
[LinearRegChVar] Decimal(18,4),
[LinearRegCurve] Decimal(18,4),
[LinearRegTrendline] Decimal(18,4),
[LinearRegrReversal] Decimal(18,4),
[LinearRegressionSlope] Decimal(18,4),
[Long-term Debt to Capital - Current (LTM)] Decimal(18,4),
[LongHaulFilter] integer,
[LongLeggedDoji] integer,
[LookUpHighest] Decimal(18,4),
[LookUpLowest] Decimal(18,4),
[Low] Decimal(18,4),
[LowPriceGappingPlay] Decimal(18,4),
[MACD] Decimal(18,4),
[MACDHistogram] Decimal(18,4),
[MACDHistogramCrossover] Decimal(18,4),
[MACDTwoLines] Decimal(18,4),
[MACDWithPrices] Decimal(18,4),
[MAD] Decimal(18,4),
[MADH] Decimal(18,4),
[MESASineWave] Decimal(18,4),
[MF_pct] Decimal(18,4),
[MajorGannLevels] Decimal(18,4),
[Mark] Decimal(18,4),
[Mark %Change] Decimal(18,4),
[Mark % of underlying value] Decimal(18,4),
[Mark Change] Decimal(18,4),
[MarkerIndicator] Decimal(18,4),
[Market Cap / Common Equity Ratio - Current] Decimal(18,4),
[Market Cap] varchar(50),
[Market Maker Move] varchar(50),
[MarketForecast] Decimal(18,4),
[MarketSentiment] Decimal(18,4),
[Marubozu] integer,
[MassIndex] Decimal(18,4),
[MatHold] integer,
[MatchingLow] integer,
[Max Cov Return] varchar(50),
[McClellanOscillator] Decimal(18,4),
[McClellanSummationIndex] Decimal(18,4),
[MedianAverage] Decimal(18,4),
[MedianPrice] Decimal(18,4),
[MeetingLines] Decimal(18,4),
[MiddleHighLowMA] Decimal(18,4),
[MktFacilitationIdx] Decimal(18,4),
[ModifiedTrueRange] Decimal(18,4),
[Momentum] Decimal(18,4),
[MomentumCrossover] integer,
[MomentumPercent] Decimal(18,4),
[MomentumPercentDiff] Decimal(18,4),
[MomentumSMA] Decimal(18,4),
[MoneyFlow] Decimal(18,4),
[MoneyFlowIndex] Decimal(18,4),
[MoneyFlowIndexCrossover] Decimal(18,4),
[MoneyFlowOscillator] Decimal(18,4),
[MonkeyBars] Decimal(18,4),
[MonthlySeasonality] Decimal(18,4),
[MorningDojiStar] Decimal(18,4),
[MorningStar] Decimal(18,4),
[MovAvgAdaptive] Decimal(18,4),
[MovAvgBandWidth] Decimal(18,4),
[MovAvgBands] Decimal(18,4),
[MovAvgEnvelope] Decimal(18,4),
[MovAvgExpRibbon] Decimal(18,4),
[MovAvgExponential] Decimal(18,4),
[MovAvgTriangular] Decimal(18,4),
[MovAvgTwoLines] Decimal(18,4),
[MovAvgWeighted] Decimal(18,4),
[MovingAvgCrossover] Decimal(18,4),
[MultiCurrencyCorrelationOsc] Decimal(18,4),
[MyRSIWithNET] Decimal(18,4),
[NegativeVolumeIndex] Decimal(18,4),
[Net Chng] Decimal(18,4),
[Net Income - Current] Decimal(18,4),
[Net Profit Margin - Current (LTM)] Decimal(18,4),
[Next3rdFriday] Decimal(18,4),
[OnBalanceVolume] Decimal(18,4),
[OnBalanceVolumeModified] Decimal(18,4),
[OnNeck] Decimal(18,4),
[OneBlackCrow] Decimal(18,4),
[OneWhiteSoldier] Decimal(18,4),
[One_Hundred_SMA_pct_Change] Decimal(18,4),
[One_Mo_Chg] Decimal(18,4),
[One_Yr_Chg] Decimal(18,4),
[OnsetTrendDetector] Decimal(18,4),
[Open] Decimal(18,4),
[Open.Int] Decimal(18,4),
[OpenInterest] Decimal(18,4),
[Operating Profit Margin - Current (LTM)] Decimal(18,4),
[OptionDelta] Decimal(18,4),
[OptionGamma] Decimal(18,4),
[OptionRho] Decimal(18,4),
[OptionTheta] Decimal(18,4),
[OptionVega] Decimal(18,4),
[P/L Day] Decimal(18,4),
[P/L Open] Decimal(18,4),
[P/L %] Decimal(18,4),
[P/L Year] Decimal(18,4),
[PE] Decimal(18,4),
[PMC] Decimal(18,4),
[PMO] Decimal(18,4),
[PPS] Decimal(18,4),
[PairCorrelation] Decimal(18,4),
[PairRatio] Decimal(18,4),
[ParabolicSAR] Decimal(18,4),
[ParabolicSARCrossover] Decimal(18,4),
[PercentChg] Decimal(18,4),
[PercentR] Decimal(18,4),
[PersonsPivots] Decimal(18,4),
[PiercingLine] Decimal(18,4),
[PivotPoints] Decimal(18,4),
[PolarizedFractalEfficiency] Decimal(18,4),
[PolychromMtm] Decimal(18,4),
[Net Liq] Decimal(18,4),
[Pos Qty] Decimal(18,4),
[PositiveVolumeIndex] Decimal(18,4),
[Price / Book Value Ratio - Current] Decimal(18,4),
[Price / Cash Flow Ratio - Current] Decimal(18,4),
[Price / Earnings Ratio - Current] Decimal(18,4),
[PriceActionIndicator] Decimal(18,4),
[PriceAndVolumeTrend] Decimal(18,4),
[PriceAverageCrossover] Decimal(18,4),
[PriceChannel] Decimal(18,4),
[PriceOsc] Decimal(18,4),
[PriceRatio] Decimal(18,4),
[PriceTimeFilteringAccVolume] Decimal(18,4),
[PriceTimeFilteringBarCount] Decimal(18,4),
[PriceVolumeRank] Decimal(18,4),
[PriceZoneOscillator] Decimal(18,4),
[Prob.ITM] Decimal(18,4),
[Prob.OTM] Decimal(18,4),
[Prob.Touch] Decimal(18,4),
[ProjectionBands] Decimal(18,4),
[ProjectionOscillator] Decimal(18,4),
[Put Sizzle Index] Decimal(18,4),
[P/C Ratio] Decimal(18,4),
[QStick] Decimal(18,4),
[Quick Ratio - Current (LTM)] Decimal(18,4),
"Quote Trend" varchar(max),
[RDOC] Decimal(18,4),
[RSI] Decimal(18,4),
[RSICrossover] Decimal(18,4),
[RSIH] Decimal(18,4),
[RSI_Colorized] Decimal(18,4),
[RSMK] Decimal(18,4),
[RS_VA_EMA] Decimal(18,4),
[RSquared] Decimal(18,4),
[RainbowAverage] Decimal(18,4),
[RandomWalkIndex] Decimal(18,4),
[RangeBands] Decimal(18,4),
[RangeIndicator] Decimal(18,4),
[RateOfChange] Decimal(18,4),
[RateOfChangeCrossover] Decimal(18,4),
[RateOfChangeWithBands] Decimal(18,4),
[Ray] Decimal(18,4),
[RayBearPower] Decimal(18,4),
[RayBullPower] Decimal(18,4),
[RecursiveMedianFilter] Decimal(18,4),
[RecursiveMedianOscillator] Decimal(18,4),
[Reflex] Decimal(18,4),
[RegressionDivergence] Decimal(18,4),
[RelativeMomentumIndex] Decimal(18,4),
[RelativeRangeIndex] Decimal(18,4),
[RelativeStrength] Decimal(18,4),
[RelativeVolatilityIndex] Decimal(18,4),
[RelativeVolumeStDev] Decimal(18,4),
[Return on Assets (ROA) - Current (LTM)] Decimal(18,4),
[ROC] Decimal(18,4),
[Return on Equity (ROE) - Current (LTM)] Decimal(18,4),
[ROR] Decimal(18,4),
[Revenue - Current] Decimal(18,4),
[ReverseEMA] Decimal(18,4),
[ReverseEngineeringMACD] Decimal(18,4),
[ReverseEngineeringRSI] Decimal(18,4),
[Rho] Decimal(18,4),
[RibbonStudy] Decimal(18,4),
[RisingThreeMethods] Decimal(18,4),
[RocketRSI] Decimal(18,4),
[STARCBands] Decimal(18,4),
[SVEPivots] Decimal(18,4),
[SVEStochRSI] Decimal(18,4),
[SVEZLRBPercB] Decimal(18,4),
[Sales Per Share - Current (LTM)] Decimal(18,4),
[SchaffTrendCycle] Decimal(18,4),
[Sector] varchar(50),
[SectorRotationModel] varchar(50),
[SemiCupFormation] Decimal(18,4),
"1" varchar(50),
"2" varchar(50),
"3" varchar(50),
"4" varchar(50),
"5" varchar(50),
"6" varchar(50),
"7" varchar(50),
"8" varchar(50),
"9" varchar(50),
[SentimentZoneOscillator] Decimal(18,4),
[SeparatingLines] Decimal(18,4),
[SequenceCounter] Decimal(18,4),
[SeriesCount] Decimal(18,4),
[Shares] Decimal(18,4),
[ShootingStar] Decimal(18,4),
[Short Sale Borrowing Rate(%)] Decimal(18,4),
[SideBySideWhiteLines] Decimal(18,4),
[SimpleMovingAvg] Decimal(18,4),
[SimpleTrendChannelFilter] Decimal(18,4),
[Six_Mo_Chg] Decimal(18,4),
[Size] varchar(50),
[Sizzle Index] Decimal(18,4),
[SlowRSI] Decimal(18,4),
[SlowVSI] Decimal(18,4),
[24h/168h Social Activity Ratio] Decimal(18,4),
[24h/56d Social Activity Ratio] Decimal(18,4),
[1h/168h Social Activity Ratio] Decimal(18,4),
[168h/56d Social Activity Ratio] Decimal(18,4),
[168h_mavg Mentions Count] Decimal(18,4),
[1d_count Mentions Count] Decimal(18,4),
[1h_count Mentions Count] Decimal(18,4),
[SoftAndHardLimiterComparison] Decimal(18,4),
[Spearman] Decimal(18,4),
[SpectrumBars] Decimal(18,4),
[Spreads] Decimal(18,4),
[StandardDevChannel] Decimal(18,4),
[StandardDeviation] Decimal(18,4),
[StandardError] Decimal(18,4),
[StandardErrorBands] Decimal(18,4),
[StandardErrorChannel] Decimal(18,4),
[StickSandwich] Decimal(18,4),
[Stiffness] Decimal(18,4),
[StochRSI] Decimal(18,4),
[StochasticCrossover] Decimal(18,4),
[StochasticFast] Decimal(18,4),
[StochasticFull] Decimal(18,4),
[StochasticFullDiff] Decimal(18,4),
[StochasticMACD] Decimal(18,4),
[StochasticMomentumIndex] Decimal(18,4),
[StochasticSlow] Decimal(18,4),
"StrengthMeter" varchar(50),
[StressIndicator] Decimal(18,4),
"Strike" Decimal(18,4),
[Sub-Industry] varchar(max),
[SuperPassbandFilter] Decimal(18,4),
[SwamiAccDist] Decimal(18,4),
[SwamiConvolution] Decimal(18,4),
[SwamiIntradayFisher] Decimal(18,4),
[SwamiIntradayImpulse] Decimal(18,4),
[SwamiIntradayVolume] Decimal(18,4),
[SwamiLaguerreTrend] Decimal(18,4),
[SwamiMarketMode] Decimal(18,4),
[SwamiPredict] Decimal(18,4),
[SwamiRelativePerformance] Decimal(18,4),
[SwamiSwingWave] Decimal(18,4),
[SwamiVolatility] Decimal(18,4),
[SwamiVolume] Decimal(18,4),
[SwingIndex] Decimal(18,4),
[SymbolRelation] Decimal(18,4),
[TAC_ADX] Decimal(18,4),
[TAC_DIMinus] Decimal(18,4),
[TAC_DIPlus] Decimal(18,4),
[TEMA] Decimal(18,4),
[TMV] Decimal(18,4),
[TPOProfile] Decimal(18,4),
[TRIX] Decimal(18,4),
[TTM_LRC] Decimal(18,4),
[TTM_ScalperAlert] Decimal(18,4),
[TTM_Squeeze] Decimal(18,4),
[TTM_Trend] Decimal(18,4),
[TTM_Wave] Decimal(18,4),
[Tax Rate - Current (LTM)] Decimal(18,4),
[TechnicalStockRating] Decimal(18,4),
[Theo Price] Decimal(18,4),
[TheoreticalOptionPrice] Decimal(18,4),
[Theta] Decimal(18,4),
[ThreeBlackCrows] Decimal(18,4),
[ThreeInsideDown] Decimal(18,4),
[ThreeInsideUp] Decimal(18,4),
[ThreeLineStrike] Decimal(18,4),
[ThreeOutsideDown] Decimal(18,4),
[ThreeOutsideUp] Decimal(18,4),
[ThreeStarsInTheSouth] Decimal(18,4),
[ThreeWhiteSoldiers] Decimal(18,4),
[Thrusting] Decimal(18,4),
[Tick Size] Decimal(18,4),
[Tick Value] Decimal(18,4),
[TimeSeriesForecast] Decimal(18,4),
"Day Close" Decimal(18,4),
[Total Asset Turnover - Current (LTM)] Decimal(18,4),
[Total Cost] Decimal(18,4),
[TradeVolumeIndex] Decimal(18,4),
[TrendNoiseBalance] Decimal(18,4),
[TrendPeriods] Decimal(18,4),
[TrendPersistenceRate] Decimal(18,4),
[TrendQuality] Decimal(18,4),
[Trendflex] Decimal(18,4),
[TriStar] Decimal(18,4),
[TrueRangeAdjEMA] Decimal(18,4),
[TrueRangeIndicator] Decimal(18,4),
[TrueRangeSpecifiedVolume] Decimal(18,4),
[TrueStrengthIndex] Decimal(18,4),
[Twenty_Day_Chg] Decimal(18,4),
[Twenty_SMA_pct_Change] Decimal(18,4),
[TwoCrows] Decimal(18,4),
[Two_Hundred_SMA_pct_Change] Decimal(18,4),
[TypicalPrice] Decimal(18,4),
[UlcerIndex] Decimal(18,4),
[UltimateOscillator] Decimal(18,4),
[Underlying_Last] Decimal(18,4),
[UndersampledDoubleMovAvg] Decimal(18,4),
[UniqueThreeRiverBottom] Decimal(18,4),
[UniversalOscillator] Decimal(18,4),
[UpsideGapThreeMethods] Decimal(18,4),
[UpsideGapTwoCrows] Decimal(18,4),
[UpsideTasukiGap] Decimal(18,4),
[VPNIndicator] Decimal(18,4),
[VWAP] Decimal(18,4),
[VariableMA] Decimal(18,4),
[Vega] Decimal(18,4),
[VerticalHorizontalFilter] Decimal(18,4),
[Vol Diff] Decimal(18,4),
[Vol Index] Decimal(18,4),
[VolSizzle] Decimal(18,4),
[VolatilityStdDev] Decimal(18,4),
[VolatilitySwitch] Decimal(18,4),
[Volume] Decimal(18,4),
[VolumeAccumulation] Decimal(18,4),
[VolumeAvg] Decimal(18,4),
[VolumeFlowIndicator] Decimal(18,4),
[VolumeOsc] Decimal(18,4),
[VolumeProfile] Decimal(18,4),
[VolumeRateOfChange] Decimal(18,4),
[VolumeWeightedMACD] Decimal(18,4),
[VolumeZoneOscillator] Decimal(18,4),
[VortexIndicator] Decimal(18,4),
[VossPredictiveFilter] Decimal(18,4),
[WarningSymbols] Decimal(18,4),
[WeaknessInAStrongTrend] Decimal(18,4),
[WeeklyAndDailyMACD] Decimal(18,4),
[WeeklyAndDailyPPO] Decimal(18,4),
[Weighted Back Vol] Decimal(18,4),
[WeightedClose] Decimal(18,4),
[WildersSmoothing] Decimal(18,4),
[WilliamsAD] Decimal(18,4),
[WilliamsAlligator] Decimal(18,4),
[WilliamsFractal] Decimal(18,4),
[WilliamsPercentR] Decimal(18,4),
[WoodiesPivots] Decimal(18,4),
[YTD_Chg] Decimal(18,4),
[YearlyRelativeRange] Decimal(18,4),
[Close] Decimal(18,4),
[Yield] Decimal(18,4),
[ZigZagHighLow] Decimal(18,4),
[ZigZagPercent] Decimal(18,4),
[ZigZagSign] Decimal(18,4),
[ZigZagStepPattern] Decimal(18,4),
[ZigZagTrendPercent] Decimal(18,4),
[ZigZagTrendSign] Decimal(18,4),
[pct_1_Mo_Chg] Decimal(18,4),
[pct_1_Yr_Chg] Decimal(18,4),
[pct_20_Day_Chg] Decimal(18,4),
[pct_5_Day_Chg] Decimal(18,4),
[pct_6_Mo_Chg] Decimal(18,4),
[pct_Chg_Open] Decimal(18,4),
[pct_Chg_from_52Wk_Hi] Decimal(18,4),
[pct_Chg_from_52Wk_Lo] Decimal(18,4),
[pct_YTD_Chg] Decimal(18,4)
)
GO

/****** Object:  Table [dbo].[StocksUSA]    Script Date: 10/8/2024 3:05:53 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[StocksUSAColumnar]') AND type in (N'U'))
DROP TABLE [dbo].[StocksUSAColumnar]
GO

CREATE TABLE [dbo].[StocksUSAColumnar] (
[ID] int NOT NULL IDENTITY(1,1) PRIMARY KEY,
[Description] varchar(50),
[Symbol] varchar(50),
[EX] varchar(50),
[DATE] date,
[DAYOFWEEK] varchar(50),
[Market CapnNEW] varchar(50),
[%Change] Decimal(18,4),
[% In The Money] Decimal(18,4),
[% Out Of The Money] Decimal(18,4),
[52High]Decimal(18,4),
[52Low] Decimal(18,4),
[ADX] Decimal(18,4),
[ADXBreakoutsFilter] Decimal(18,4),
[ADXCrossover] Decimal(18,4),
[ADXR] Decimal(18,4),
[AM_Detector] Decimal(18,4),
[APTR] Decimal(18,4),
[ARSI] Decimal(18,4),
[ATR] Decimal(18,4),
[ATRHighSMABreakoutsFilter] Decimal(18,4),
[ATRTrailingStop] Decimal(18,4),
[AbandonedBaby] Decimal(18,4),
[AccDist] Decimal(18,4),
[AccelerationBands] Decimal(18,4),
[AccelerationDecelerationOsc] Decimal(18,4),
[AccumDistBuyPr] Decimal(18,4),
[AccumDistPrVol] Decimal(18,4),
[AccumulationDistribution] Decimal(18,4),
[AccumulationSwingIndex] Decimal(18,4),
[AdaptiveEMA] Decimal(18,4),
[AdvanceBlock] Decimal(18,4),
[AdvanceDecline] Decimal(18,4),
[AdvanceDeclineCumulativeAvg] Decimal(18,4),
[Alpha2] Decimal(18,4),
[AlphaJensen] Decimal(18,4),
[AnchoredVWAP] Decimal(18,4),
[AroonIndicator] Decimal(18,4),
[AroonOscillator] Decimal(18,4),
[Ask] Decimal(18,4),
[AS] Decimal(18,4),
[AX] varchar(1),
[Avg Price] Decimal(18,4),
[Avg_Vol_YTD] Decimal(18,4),
[AwesomeOscillator] Decimal(18,4),
[BBDivergence] Decimal(18,4),
[Back Expected Move] varchar(50),
[Back Vol] Decimal(18,4),
[BalanceOfMarketPower] Decimal(18,4),
[BandpassFilter] Decimal(18,4),
[BeltHold] Decimal(18,4),
[Beta] Decimal(18,4),
[Beta1] Decimal(18,4),
[Beta2] Decimal(18,4),
[Bid] Decimal(18,4),
[BS] Decimal(18,4),
[BX] varchar(50),
[BollingerBands] Decimal(18,4),
[BollingerBandsCrossover] Decimal(18,4),
[BollingerBandwidth] Decimal(18,4),
[BollingerPercentB] Decimal(18,4),
[Book Value Per Share - Current (LTM)] Decimal(18,4),
[Book Value Per Share Growth - Current] Decimal(18,4),
[Breakaway] Decimal(18,4),
[CAM_Indicator] Decimal(18,4),
[CCI] Decimal(18,4),
[CCIAverage] Decimal(18,4),
[CPMO] Decimal(18,4),
[CSI] Decimal(18,4),
[Call Sizzle Index] Decimal(18,4),
[CamarillaPoints] Decimal(18,4),
[Cash Flow Per Share - Current (LTM)] Decimal(18,4),
[ChaikinMoneyFlow] Decimal(18,4),
[ChaikinOsc] Decimal(18,4),
[ChaikinOscillator] Decimal(18,4),
[ChaikinVolatility] Decimal(18,4),
[ChandeMomentumOscillator] Decimal(18,4),
[Chg_Open] Decimal(18,4),
[CloseLocationValue] Decimal(18,4),
[Company Address - City] varchar(50),
[Company Address - Nation] varchar(50),
[Company Address - State] varchar(50),
[Company Address - Street] varchar(max),
[Company Address - Zip] varchar(50),
[Company Name] varchar(200),
[Company Phone] varchar(50),
[Company Website] varchar(100),
[ConcealingBabySwallow] Decimal(18,4),
[CondensedCandles] Decimal(18,4),
[CongAdaptiveMovingAverage] Decimal(18,4),
[Correlation] Decimal(18,4),
[CorrelationCycleAngle] Decimal(18,4),
[CorrelationCycleIndicator] Decimal(18,4),
[CorrelationCycleMarketState] Decimal(18,4),
[CorrelationTrendIndicator] Decimal(18,4),
[Cost] Decimal(18,4),
[Cov Return] Decimal(18,4),
[CumulativeOvernightVolume] Decimal(18,4),
[CumulativeVolumeIndex] Decimal(18,4),
[Current Ratio - Current (LTM)] Decimal(18,4),
[Cusip] varchar(50),
"Custom 1" Decimal(18,4),
"Custom 2" Decimal(18,4),
"Custom 3" Decimal(18,4),
"Custom 4" Decimal(18,4),
"Custom 5" Decimal(18,4),
"Custom 6" Decimal(18,4),
"Custom 7" Decimal(18,4),
"Custom 8" Decimal(18,4),
"Custom 9" Decimal(18,4),
"Custom10" Decimal(18,4),
"Custom11" Decimal(18,4),
"Custom12" Decimal(18,4),
"Custom13" Decimal(18,4),
"Custom14" Decimal(18,4),
"Custom15" Decimal(18,4),
"Custom16" Decimal(18,4),
"Custom17" Decimal(18,4),
"Custom18" Decimal(18,4),
"Custom19" Decimal(18,4),
[CyberCyclesOscillator] Decimal(18,4),
[CycleTrendAnalytics] Decimal(18,4),
[DEMA] Decimal(18,4),
[DIMinus] Decimal(18,4),
[DIPlus] Decimal(18,4),
[DMA] Decimal(18,4),
[DMH] Decimal(18,4),
[DMI] Decimal(18,4),
[DMI_Oscillator] Decimal(18,4),
[DMI_ReversalAlerts] Decimal(18,4),
[DMI_StochasticExtreme] Decimal(18,4),
[DailyHighLow] Decimal(18,4),
[DailyOpen] Decimal(18,4),
[DailyRelativeRange] varchar(50),
[DailySMA] Decimal(18,4),
[DarkCloudCover] Decimal(18,4),
[DarvasBox] Decimal(18,4),
[Date of Incorporation] date,
[Days] Decimal(18,4),
[Deliberation] Decimal(18,4),
[Delta] Decimal(18,4),
[DemandIndex] Decimal(18,4),
[DetrendedPriceOsc] Decimal(18,4),
[DeviationScaledMovAvg] Decimal(18,4),
[DeviationScaledOscillator] Decimal(18,4),
[DisparityIndex] Decimal(18,4),
[DisplacedEMA] Decimal(18,4),
[Displacer] Decimal(18,4),
[Div] Decimal(18,4),
[Div.Freq] varchar(50),
[Div. Payout (% of Earnings) - Current (LTM)] Decimal(18,4),
[Div. Payout Per Share (% of EPS) - Current] Decimal(18,4),
[Div. Per Share - Current] Decimal(18,4),
[Div. Per Share - TTM - Current (LTM)] Decimal(18,4),
[Div. Yield - Current] Decimal(18,4),
[Doji] integer,
[Dollar_Volume] Decimal(18,4),
[DoubleSmoothedStochastic] Decimal(18,4),
[DownsideGapThreeMethods] Decimal(18,4),
[DownsideTasukiGap] Decimal(18,4),
[DynamicMomentumIndex] Decimal(18,4),
[EBITDA - Current] Decimal(18,4),
[EPR Lower] Decimal(18,4),
[EPR Upper] Decimal(18,4),
[EPS] Decimal(18,4),
[ESDBands] Decimal(18,4),
[Earnings Per Share - Current] Decimal(18,4),
[Earnings Per Share - TTM - Current (LTM)] Decimal(18,4),
[EaseOfMovement] Decimal(18,4),
[EfficiencyRatio] Decimal(18,4),
[EhlersAutocorrelation] Decimal(18,4),
[EhlersAutocorrelationPeriodogram] Decimal(18,4),
[EhlersDecyclerOscillator] Decimal(18,4),
[EhlersDistantCoefficientFilter] Decimal(18,4),
[EhlersHighpassFilter] Decimal(18,4),
[EhlersRoofingFilter] Decimal(18,4),
[EhlersSimpleDecycler] Decimal(18,4),
[EhlersStochastic] Decimal(18,4),
[EhlersSuperSmootherFilter] Decimal(18,4),
[ElegantOscillator] Decimal(18,4),
[ElliotOscillator] Decimal(18,4),
[Engulfing] integer,
[ErgodicOsc] Decimal(18,4),
[Ermanometry] integer,
[EveningDojiStar] integer,
[EveningStar] integer,
[Ex Div.Date] date,
[Expected Move Diff] varchar(50),
[ExponentialDeviationBands] Decimal(18,4),
[Extrinsic] Decimal(18,4),
[FIR_FiltersOfPriceChange] Decimal(18,4),
[FIR_Hamming] Decimal(18,4),
[FIR_Hann] Decimal(18,4),
[FIR_TriangleWeighting] Decimal(18,4),
[FM_Demodulator] Decimal(18,4),
[FM_Demodulator2] Decimal(18,4),
[FW_CCI_Advanced] Decimal(18,4),
[FW_CCI_Basic] Decimal(18,4),
[FW_DPO_MOBO] Decimal(18,4),
[FW_FisherTransformer] Decimal(18,4),
[FW_MMG] Decimal(18,4),
[FW_MOBO_Advanced] Decimal(18,4),
[FW_MOBO_Basic] Decimal(18,4),
[FW_SOAP] Decimal(18,4),
[FallingThreeMethods] Decimal(18,4),
[FastBeta] Decimal(18,4),
[Fifty_SMA_pct_Change] Decimal(18,4),
[Financial Leverage (Assets/Equity) - Current (LTM)] Decimal(18,4),
[FisherTransform] Decimal(18,4),
[Five_Day_Chg] Decimal(18,4),
[Fixed Charge Coverage Ratio - Current (LTM)] Decimal(18,4),
[ForceIndex] Decimal(18,4),
[ForecastOscillator] Decimal(18,4),
[FourPercentModel] Decimal(18,4),
[FourierSeriesIndicator] Decimal(18,4),
[Free Cash Flow Per Share - Current (LTM)] Decimal(18,4),
[FreedomOfMovement] Decimal(18,4),
[Front Expected Move] varchar(50),
[Front Vol] Decimal(18,4),
[Gamma] Decimal(18,4),
[GapMomentum] Decimal(18,4),
[GatorOscillator] Decimal(18,4),
[Gross Profit Margin - Current (LTM)] Decimal(18,4),
[HACOLT] Decimal(18,4),
[HHLLS] Decimal(18,4),
[HLVolatility] Decimal(18,4),
[HTB/ETB] varchar(3),
[HV_Percentile] Decimal(18,4),
[Hammer] integer,
[HangingMan] integer,
[Harami] integer,
[HaramiCross] integer,
[HeikinAshiDiff] Decimal(18,4),
[HiLoActivator] Decimal(18,4),
[High] Decimal(18,4),
[High/Low Graph] Decimal(18,4),
[HighPriceGappingPlay] integer,
[HistoricalVolatility] Decimal(18,4),
[HomingPigeon] integer,
[HullMovingAvg] Decimal(18,4),
[IFT_StochOsc] Decimal(18,4),
[IV_Percentile] Decimal(18,4),
[Ichimoku] Decimal(18,4),
[IdenticalThreeCrows] integer,
[ImpVolatility] Decimal(18,4),
[Impl Vol] Decimal(18,4),
[Impulse] integer,
[InNeck] integer,
[Industry] varchar(200),
[Inertia] Decimal(18,4),
[Initial Margin] varchar(50),
[Interest Rate - Estimated Average - Current (LTM)] Decimal(18,4),
[IntradayFlagFormation] integer,
[IntradayMomentumIndex] Decimal(18,4),
[Intrinsic] varchar(100),
[Inventory Turnover - Current (LTM)] Decimal(18,4),
[InvertedHammer] integer,
[KeltnerChannels] Decimal(18,4),
[Kicking] integer,
[KlingerHistogram] Decimal(18,4),
[KlingerOscillator] Decimal(18,4),
[LBR_PaintBars] integer,
[LBR_SmartADX] Decimal(18,4),
[LBR_ThreeTenOscillator] Decimal(18,4),
[Last] Decimal(18,4),
[Last Annual Filing Date] date,
[Last Interim Filing Date] date,
[Last Size] Decimal(18,4),
--[Last] Decimal(18,4),
[LX] varchar(50),
[LeavittConvolution] Decimal(18,4),
[LeavittConvolutionAcceleration] Decimal(18,4),
[LeavittConvolutionSlope] Decimal(18,4),
[LegacyEMA] Decimal(18,4),
[LinearRegAdjEMA] Decimal(18,4),
[LinearRegCh100] Decimal(18,4),
[LinearRegCh50] Decimal(18,4),
[LinearRegChVar] Decimal(18,4),
[LinearRegCurve] Decimal(18,4),
[LinearRegTrendline] Decimal(18,4),
[LinearRegrReversal] Decimal(18,4),
[LinearRegressionSlope] Decimal(18,4),
[Long-term Debt to Capital - Current (LTM)] Decimal(18,4),
[LongHaulFilter] integer,
[LongLeggedDoji] integer,
[LookUpHighest] Decimal(18,4),
[LookUpLowest] Decimal(18,4),
[Low] Decimal(18,4),
[LowPriceGappingPlay] Decimal(18,4),
[MACD] Decimal(18,4),
[MACDHistogram] Decimal(18,4),
[MACDHistogramCrossover] Decimal(18,4),
[MACDTwoLines] Decimal(18,4),
[MACDWithPrices] Decimal(18,4),
[MAD] Decimal(18,4),
[MADH] Decimal(18,4),
[MESASineWave] Decimal(18,4),
[MF_pct] Decimal(18,4),
[MajorGannLevels] Decimal(18,4),
[Mark] Decimal(18,4),
[Mark %Change] Decimal(18,4),
[Mark % of underlying value] Decimal(18,4),
[Mark Change] Decimal(18,4),
[MarkerIndicator] Decimal(18,4),
[Market Cap / Common Equity Ratio - Current] Decimal(18,4),
[Market Cap] varchar(50),
[Market Maker Move] varchar(50),
[MarketForecast] Decimal(18,4),
[MarketSentiment] Decimal(18,4),
[Marubozu] integer,
[MassIndex] Decimal(18,4),
[MatHold] integer,
[MatchingLow] integer,
[Max Cov Return] varchar(50),
[McClellanOscillator] Decimal(18,4),
[McClellanSummationIndex] Decimal(18,4),
[MedianAverage] Decimal(18,4),
[MedianPrice] Decimal(18,4),
[MeetingLines] Decimal(18,4),
[MiddleHighLowMA] Decimal(18,4),
[MktFacilitationIdx] Decimal(18,4),
[ModifiedTrueRange] Decimal(18,4),
[Momentum] Decimal(18,4),
[MomentumCrossover] integer,
[MomentumPercent] Decimal(18,4),
[MomentumPercentDiff] Decimal(18,4),
[MomentumSMA] Decimal(18,4),
[MoneyFlow] Decimal(18,4),
[MoneyFlowIndex] Decimal(18,4),
[MoneyFlowIndexCrossover] Decimal(18,4),
[MoneyFlowOscillator] Decimal(18,4),
[MonkeyBars] Decimal(18,4),
[MonthlySeasonality] Decimal(18,4),
[MorningDojiStar] Decimal(18,4),
[MorningStar] Decimal(18,4),
[MovAvgAdaptive] Decimal(18,4),
[MovAvgBandWidth] Decimal(18,4),
[MovAvgBands] Decimal(18,4),
[MovAvgEnvelope] Decimal(18,4),
[MovAvgExpRibbon] Decimal(18,4),
[MovAvgExponential] Decimal(18,4),
[MovAvgTriangular] Decimal(18,4),
[MovAvgTwoLines] Decimal(18,4),
[MovAvgWeighted] Decimal(18,4),
[MovingAvgCrossover] Decimal(18,4),
[MultiCurrencyCorrelationOsc] Decimal(18,4),
[MyRSIWithNET] Decimal(18,4),
[NegativeVolumeIndex] Decimal(18,4),
[Net Chng] Decimal(18,4),
[Net Income - Current] Decimal(18,4),
[Net Profit Margin - Current (LTM)] Decimal(18,4),
[Next3rdFriday] Decimal(18,4),
[OnBalanceVolume] Decimal(18,4),
[OnBalanceVolumeModified] Decimal(18,4),
[OnNeck] Decimal(18,4),
[OneBlackCrow] Decimal(18,4),
[OneWhiteSoldier] Decimal(18,4),
[One_Hundred_SMA_pct_Change] Decimal(18,4),
[One_Mo_Chg] Decimal(18,4),
[One_Yr_Chg] Decimal(18,4),
[OnsetTrendDetector] Decimal(18,4),
[Open] Decimal(18,4),
[Open.Int] Decimal(18,4),
[OpenInterest] Decimal(18,4),
[Operating Profit Margin - Current (LTM)] Decimal(18,4),
[OptionDelta] Decimal(18,4),
[OptionGamma] Decimal(18,4),
[OptionRho] Decimal(18,4),
[OptionTheta] Decimal(18,4),
[OptionVega] Decimal(18,4),
[P/L Day] Decimal(18,4),
[P/L Open] Decimal(18,4),
[P/L %] Decimal(18,4),
[P/L Year] Decimal(18,4),
[PE] Decimal(18,4),
[PMC] Decimal(18,4),
[PMO] Decimal(18,4),
[PPS] Decimal(18,4),
[PairCorrelation] Decimal(18,4),
[PairRatio] Decimal(18,4),
[ParabolicSAR] Decimal(18,4),
[ParabolicSARCrossover] Decimal(18,4),
[PercentChg] Decimal(18,4),
[PercentR] Decimal(18,4),
[PersonsPivots] Decimal(18,4),
[PiercingLine] Decimal(18,4),
[PivotPoints] Decimal(18,4),
[PolarizedFractalEfficiency] Decimal(18,4),
[PolychromMtm] Decimal(18,4),
[Net Liq] Decimal(18,4),
[Pos Qty] Decimal(18,4),
[PositiveVolumeIndex] Decimal(18,4),
[Price / Book Value Ratio - Current] Decimal(18,4),
[Price / Cash Flow Ratio - Current] Decimal(18,4),
[Price / Earnings Ratio - Current] Decimal(18,4),
[PriceActionIndicator] Decimal(18,4),
[PriceAndVolumeTrend] Decimal(18,4),
[PriceAverageCrossover] Decimal(18,4),
[PriceChannel] Decimal(18,4),
[PriceOsc] Decimal(18,4),
[PriceRatio] Decimal(18,4),
[PriceTimeFilteringAccVolume] Decimal(18,4),
[PriceTimeFilteringBarCount] Decimal(18,4),
[PriceVolumeRank] Decimal(18,4),
[PriceZoneOscillator] Decimal(18,4),
[Prob.ITM] Decimal(18,4),
[Prob.OTM] Decimal(18,4),
[Prob.Touch] Decimal(18,4),
[ProjectionBands] Decimal(18,4),
[ProjectionOscillator] Decimal(18,4),
[Put Sizzle Index] Decimal(18,4),
[P/C Ratio] Decimal(18,4),
[QStick] Decimal(18,4),
[Quick Ratio - Current (LTM)] Decimal(18,4),
"Quote Trend" varchar(max),
[RDOC] Decimal(18,4),
[RSI] Decimal(18,4),
[RSICrossover] Decimal(18,4),
[RSIH] Decimal(18,4),
[RSI_Colorized] Decimal(18,4),
[RSMK] Decimal(18,4),
[RS_VA_EMA] Decimal(18,4),
[RSquared] Decimal(18,4),
[RainbowAverage] Decimal(18,4),
[RandomWalkIndex] Decimal(18,4),
[RangeBands] Decimal(18,4),
[RangeIndicator] Decimal(18,4),
[RateOfChange] Decimal(18,4),
[RateOfChangeCrossover] Decimal(18,4),
[RateOfChangeWithBands] Decimal(18,4),
[Ray] Decimal(18,4),
[RayBearPower] Decimal(18,4),
[RayBullPower] Decimal(18,4),
[RecursiveMedianFilter] Decimal(18,4),
[RecursiveMedianOscillator] Decimal(18,4),
[Reflex] Decimal(18,4),
[RegressionDivergence] Decimal(18,4),
[RelativeMomentumIndex] Decimal(18,4),
[RelativeRangeIndex] Decimal(18,4),
[RelativeStrength] Decimal(18,4),
[RelativeVolatilityIndex] Decimal(18,4),
[RelativeVolumeStDev] Decimal(18,4),
[Return on Assets (ROA) - Current (LTM)] Decimal(18,4),
[ROC] Decimal(18,4),
[Return on Equity (ROE) - Current (LTM)] Decimal(18,4),
[ROR] Decimal(18,4),
[Revenue - Current] Decimal(18,4),
[ReverseEMA] Decimal(18,4),
[ReverseEngineeringMACD] Decimal(18,4),
[ReverseEngineeringRSI] Decimal(18,4),
[Rho] Decimal(18,4),
[RibbonStudy] Decimal(18,4),
[RisingThreeMethods] Decimal(18,4),
[RocketRSI] Decimal(18,4),
[STARCBands] Decimal(18,4),
[SVEPivots] Decimal(18,4),
[SVEStochRSI] Decimal(18,4),
[SVEZLRBPercB] Decimal(18,4),
[Sales Per Share - Current (LTM)] Decimal(18,4),
[SchaffTrendCycle] Decimal(18,4),
[Sector] varchar(50),
[SectorRotationModel] varchar(50),
[SemiCupFormation] Decimal(18,4),
"1" varchar(50),
"2" varchar(50),
"3" varchar(50),
"4" varchar(50),
"5" varchar(50),
"6" varchar(50),
"7" varchar(50),
"8" varchar(50),
"9" varchar(50),
[SentimentZoneOscillator] Decimal(18,4),
[SeparatingLines] Decimal(18,4),
[SequenceCounter] Decimal(18,4),
[SeriesCount] Decimal(18,4),
[Shares] Decimal(18,4),
[ShootingStar] Decimal(18,4),
[Short Sale Borrowing Rate(%)] Decimal(18,4),
[SideBySideWhiteLines] Decimal(18,4),
[SimpleMovingAvg] Decimal(18,4),
[SimpleTrendChannelFilter] Decimal(18,4),
[Six_Mo_Chg] Decimal(18,4),
[Size] varchar(50),
[Sizzle Index] Decimal(18,4),
[SlowRSI] Decimal(18,4),
[SlowVSI] Decimal(18,4),
[24h/168h Social Activity Ratio] Decimal(18,4),
[24h/56d Social Activity Ratio] Decimal(18,4),
[1h/168h Social Activity Ratio] Decimal(18,4),
[168h/56d Social Activity Ratio] Decimal(18,4),
[168h_mavg Mentions Count] Decimal(18,4),
[1d_count Mentions Count] Decimal(18,4),
[1h_count Mentions Count] Decimal(18,4),
[SoftAndHardLimiterComparison] Decimal(18,4),
[Spearman] Decimal(18,4),
[SpectrumBars] Decimal(18,4),
[Spreads] Decimal(18,4),
[StandardDevChannel] Decimal(18,4),
[StandardDeviation] Decimal(18,4),
[StandardError] Decimal(18,4),
[StandardErrorBands] Decimal(18,4),
[StandardErrorChannel] Decimal(18,4),
[StickSandwich] Decimal(18,4),
[Stiffness] Decimal(18,4),
[StochRSI] Decimal(18,4),
[StochasticCrossover] Decimal(18,4),
[StochasticFast] Decimal(18,4),
[StochasticFull] Decimal(18,4),
[StochasticFullDiff] Decimal(18,4),
[StochasticMACD] Decimal(18,4),
[StochasticMomentumIndex] Decimal(18,4),
[StochasticSlow] Decimal(18,4),
"StrengthMeter" varchar(50),
[StressIndicator] Decimal(18,4),
"Strike" Decimal(18,4),
[Sub-Industry] varchar(max),
[SuperPassbandFilter] Decimal(18,4),
[SwamiAccDist] Decimal(18,4),
[SwamiConvolution] Decimal(18,4),
[SwamiIntradayFisher] Decimal(18,4),
[SwamiIntradayImpulse] Decimal(18,4),
[SwamiIntradayVolume] Decimal(18,4),
[SwamiLaguerreTrend] Decimal(18,4),
[SwamiMarketMode] Decimal(18,4),
[SwamiPredict] Decimal(18,4),
[SwamiRelativePerformance] Decimal(18,4),
[SwamiSwingWave] Decimal(18,4),
[SwamiVolatility] Decimal(18,4),
[SwamiVolume] Decimal(18,4),
[SwingIndex] Decimal(18,4),
[SymbolRelation] Decimal(18,4),
[TAC_ADX] Decimal(18,4),
[TAC_DIMinus] Decimal(18,4),
[TAC_DIPlus] Decimal(18,4),
[TEMA] Decimal(18,4),
[TMV] Decimal(18,4),
[TPOProfile] Decimal(18,4),
[TRIX] Decimal(18,4),
[TTM_LRC] Decimal(18,4),
[TTM_ScalperAlert] Decimal(18,4),
[TTM_Squeeze] Decimal(18,4),
[TTM_Trend] Decimal(18,4),
[TTM_Wave] Decimal(18,4),
[Tax Rate - Current (LTM)] Decimal(18,4),
[TechnicalStockRating] Decimal(18,4),
[Theo Price] Decimal(18,4),
[TheoreticalOptionPrice] Decimal(18,4),
[Theta] Decimal(18,4),
[ThreeBlackCrows] Decimal(18,4),
[ThreeInsideDown] Decimal(18,4),
[ThreeInsideUp] Decimal(18,4),
[ThreeLineStrike] Decimal(18,4),
[ThreeOutsideDown] Decimal(18,4),
[ThreeOutsideUp] Decimal(18,4),
[ThreeStarsInTheSouth] Decimal(18,4),
[ThreeWhiteSoldiers] Decimal(18,4),
[Thrusting] Decimal(18,4),
[Tick Size] Decimal(18,4),
[Tick Value] Decimal(18,4),
[TimeSeriesForecast] Decimal(18,4),
"Day Close" Decimal(18,4),
[Total Asset Turnover - Current (LTM)] Decimal(18,4),
[Total Cost] Decimal(18,4),
[TradeVolumeIndex] Decimal(18,4),
[TrendNoiseBalance] Decimal(18,4),
[TrendPeriods] Decimal(18,4),
[TrendPersistenceRate] Decimal(18,4),
[TrendQuality] Decimal(18,4),
[Trendflex] Decimal(18,4),
[TriStar] Decimal(18,4),
[TrueRangeAdjEMA] Decimal(18,4),
[TrueRangeIndicator] Decimal(18,4),
[TrueRangeSpecifiedVolume] Decimal(18,4),
[TrueStrengthIndex] Decimal(18,4),
[Twenty_Day_Chg] Decimal(18,4),
[Twenty_SMA_pct_Change] Decimal(18,4),
[TwoCrows] Decimal(18,4),
[Two_Hundred_SMA_pct_Change] Decimal(18,4),
[TypicalPrice] Decimal(18,4),
[UlcerIndex] Decimal(18,4),
[UltimateOscillator] Decimal(18,4),
[Underlying_Last] Decimal(18,4),
[UndersampledDoubleMovAvg] Decimal(18,4),
[UniqueThreeRiverBottom] Decimal(18,4),
[UniversalOscillator] Decimal(18,4),
[UpsideGapThreeMethods] Decimal(18,4),
[UpsideGapTwoCrows] Decimal(18,4),
[UpsideTasukiGap] Decimal(18,4),
[VPNIndicator] Decimal(18,4),
[VWAP] Decimal(18,4),
[VariableMA] Decimal(18,4),
[Vega] Decimal(18,4),
[VerticalHorizontalFilter] Decimal(18,4),
[Vol Diff] Decimal(18,4),
[Vol Index] Decimal(18,4),
[VolSizzle] Decimal(18,4),
[VolatilityStdDev] Decimal(18,4),
[VolatilitySwitch] Decimal(18,4),
[Volume] Decimal(18,4),
[VolumeAccumulation] Decimal(18,4),
[VolumeAvg] Decimal(18,4),
[VolumeFlowIndicator] Decimal(18,4),
[VolumeOsc] Decimal(18,4),
[VolumeProfile] Decimal(18,4),
[VolumeRateOfChange] Decimal(18,4),
[VolumeWeightedMACD] Decimal(18,4),
[VolumeZoneOscillator] Decimal(18,4),
[VortexIndicator] Decimal(18,4),
[VossPredictiveFilter] Decimal(18,4),
[WarningSymbols] Decimal(18,4),
[WeaknessInAStrongTrend] Decimal(18,4),
[WeeklyAndDailyMACD] Decimal(18,4),
[WeeklyAndDailyPPO] Decimal(18,4),
[Weighted Back Vol] Decimal(18,4),
[WeightedClose] Decimal(18,4),
[WildersSmoothing] Decimal(18,4),
[WilliamsAD] Decimal(18,4),
[WilliamsAlligator] Decimal(18,4),
[WilliamsFractal] Decimal(18,4),
[WilliamsPercentR] Decimal(18,4),
[WoodiesPivots] Decimal(18,4),
[YTD_Chg] Decimal(18,4),
[YearlyRelativeRange] Decimal(18,4),
[Close] Decimal(18,4),
[Yield] Decimal(18,4),
[ZigZagHighLow] Decimal(18,4),
[ZigZagPercent] Decimal(18,4),
[ZigZagSign] Decimal(18,4),
[ZigZagStepPattern] Decimal(18,4),
[ZigZagTrendPercent] Decimal(18,4),
[ZigZagTrendSign] Decimal(18,4),
[pct_1_Mo_Chg] Decimal(18,4),
[pct_1_Yr_Chg] Decimal(18,4),
[pct_20_Day_Chg] Decimal(18,4),
[pct_5_Day_Chg] Decimal(18,4),
[pct_6_Mo_Chg] Decimal(18,4),
[pct_Chg_Open] Decimal(18,4),
[pct_Chg_from_52Wk_Hi] Decimal(18,4),
[pct_Chg_from_52Wk_Lo] Decimal(18,4),
[pct_YTD_Chg] Decimal(18,4)
)
GO

create NonClustered ColumnStore Index [IX_StocksUSAColumnar_ColumnStore] on [StocksUSAColumnar]
(
	[%Change],
	[% In The Money],
	[% Out Of The Money],
	[52High],
	[52Low],
	[ADX],
	[ADXBreakoutsFilter],
	[ADXCrossover],
	[ADXR],
	[AM_Detector],
	[APTR],
	[ARSI],
	[ATR],
	[ATRHighSMABreakoutsFilter],
	[ATRTrailingStop],
	[AbandonedBaby],
	[AccDist],
	[AccelerationBands],
	[AccelerationDecelerationOsc],
	[AccumDistBuyPr],
	[AccumDistPrVol],
	[AccumulationDistribution],
	[AccumulationSwingIndex],
	[AdaptiveEMA],
	[AdvanceBlock],
	[AdvanceDecline],
	[AdvanceDeclineCumulativeAvg],
	[Alpha2],
	[AlphaJensen],
	[AnchoredVWAP],
	[AroonIndicator],
	[AroonOscillator],
	[Ask],
	[AS],
	[Avg Price],
	[Avg_Vol_YTD],
	[AwesomeOscillator],
	[BBDivergence],
	[Back Vol],
	[BalanceOfMarketPower],
	[BandpassFilter],
	[BeltHold],
	[Beta],
	[Beta1],
	[Beta2],
	[Bid],
	[BS],
	[BollingerBands],
	[BollingerBandsCrossover],
	[BollingerBandwidth],
	[BollingerPercentB],
	[Book Value Per Share - Current (LTM)],
	[Book Value Per Share Growth - Current],
	[Breakaway],
	[CAM_Indicator],
	[CCI],
	[CCIAverage],
	[CPMO],
	[CSI],
	[Call Sizzle Index],
	[CamarillaPoints],
	[Cash Flow Per Share - Current (LTM)],
	[ChaikinMoneyFlow],
	[ChaikinOsc],
	[ChaikinOscillator],
	[ChaikinVolatility],
	[ChandeMomentumOscillator],
	[Chg_Open],
	[CloseLocationValue],
	[ConcealingBabySwallow],
	[CondensedCandles],
	[CongAdaptiveMovingAverage],
	[Correlation],
	[CorrelationCycleAngle],
	[CorrelationCycleIndicator],
	[CorrelationCycleMarketState],
	[CorrelationTrendIndicator],
	[Cost],
	[Cov Return],
	[CumulativeOvernightVolume],
	[CumulativeVolumeIndex],
	[Current Ratio - Current (LTM)],
	"Custom 1",
	"Custom 2",
	"Custom 3",
	"Custom 4",
	"Custom 5",
	"Custom 6",
	"Custom 7",
	"Custom 8",
	"Custom 9",
	"Custom10",
	"Custom11",
	"Custom12",
	"Custom13",
	"Custom14",
	"Custom15",
	"Custom16",
	"Custom17",
	"Custom18",
	"Custom19",
	[CyberCyclesOscillator],
	[CycleTrendAnalytics],
	[DEMA],
	[DIMinus],
	[DIPlus],
	[DMA],
	[DMH],
	[DMI],
	[DMI_Oscillator],
	[DMI_ReversalAlerts],
	[DMI_StochasticExtreme],
	[DailyHighLow],
	[DailyOpen],
	[DailySMA],
	[DarkCloudCover],
	[DarvasBox],
	[Date of Incorporation],
	[Days],
	[Deliberation],
	[Delta],
	[DemandIndex],
	[DetrendedPriceOsc],
	[DeviationScaledMovAvg],
	[DeviationScaledOscillator],
	[DisparityIndex],
	[DisplacedEMA],
	[Displacer],
	[Div],
	[Div. Payout (% of Earnings) - Current (LTM)],
	[Div. Payout Per Share (% of EPS) - Current],
	[Div. Per Share - Current],
	[Div. Per Share - TTM - Current (LTM)],
	[Div. Yield - Current],
	[Doji] ,
	[Dollar_Volume],
	[DoubleSmoothedStochastic],
	[DownsideGapThreeMethods],
	[DownsideTasukiGap],
	[DynamicMomentumIndex],
	[EBITDA - Current],
	[EPR Lower],
	[EPR Upper],
	[EPS],
	[ESDBands],
	[Earnings Per Share - Current],
	[Earnings Per Share - TTM - Current (LTM)],
	[EaseOfMovement],
	[EfficiencyRatio],
	[EhlersAutocorrelation],
	[EhlersAutocorrelationPeriodogram],
	[EhlersDecyclerOscillator],
	[EhlersDistantCoefficientFilter],
	[EhlersHighpassFilter],
	[EhlersRoofingFilter],
	[EhlersSimpleDecycler],
	[EhlersStochastic],
	[EhlersSuperSmootherFilter],
	[ElegantOscillator],
	[ElliotOscillator],
	[Engulfing] ,
	[ErgodicOsc],
	[Ermanometry] ,
	[EveningDojiStar] ,
	[EveningStar] ,
	[Ex Div.Date],
	[ExponentialDeviationBands],
	[Extrinsic],
	[FIR_FiltersOfPriceChange],
	[FIR_Hamming],
	[FIR_Hann],
	[FIR_TriangleWeighting],
	[FM_Demodulator],
	[FM_Demodulator2],
	[FW_CCI_Advanced],
	[FW_CCI_Basic],
	[FW_DPO_MOBO],
	[FW_FisherTransformer],
	[FW_MMG],
	[FW_MOBO_Advanced],
	[FW_MOBO_Basic],
	[FW_SOAP],
	[FallingThreeMethods],
	[FastBeta],
	[Fifty_SMA_pct_Change],
	[Financial Leverage (Assets/Equity) - Current (LTM)],
	[FisherTransform],
	[Five_Day_Chg],
	[Fixed Charge Coverage Ratio - Current (LTM)],
	[ForceIndex],
	[ForecastOscillator],
	[FourPercentModel],
	[FourierSeriesIndicator],
	[Free Cash Flow Per Share - Current (LTM)],
	[FreedomOfMovement],
	[Front Vol],
	[Gamma],
	[GapMomentum],
	[GatorOscillator],
	[Gross Profit Margin - Current (LTM)],
	[HACOLT],
	[HHLLS],
	[HLVolatility],
	[HV_Percentile],
	[Hammer] ,
	[HangingMan] ,
	[Harami] ,
	[HaramiCross] ,
	[HeikinAshiDiff],
	[HiLoActivator],
	[High],
	[High/Low Graph],
	[HighPriceGappingPlay] ,
	[HistoricalVolatility],
	[HomingPigeon] ,
	[HullMovingAvg],
	[IFT_StochOsc],
	[IV_Percentile],
	[Ichimoku],
	[IdenticalThreeCrows] ,
	[ImpVolatility],
	[Impl Vol],
	[Impulse] ,
	[InNeck] ,
	[Inertia],
	[Interest Rate - Estimated Average - Current (LTM)],
	[IntradayFlagFormation] ,
	[IntradayMomentumIndex],
	[Inventory Turnover - Current (LTM)],
	[InvertedHammer] ,
	[KeltnerChannels],
	[Kicking] ,
	[KlingerHistogram],
	[KlingerOscillator],
	[LBR_PaintBars] ,
	[LBR_SmartADX],
	[LBR_ThreeTenOscillator],
	[Last],
	[Last Annual Filing Date],
	[Last Interim Filing Date],
	[Last Size],
	--[Last],
	[LeavittConvolution],
	[LeavittConvolutionAcceleration],
	[LeavittConvolutionSlope],
	[LegacyEMA],
	[LinearRegAdjEMA],
	[LinearRegCh100],
	[LinearRegCh50],
	[LinearRegChVar],
	[LinearRegCurve],
	[LinearRegTrendline],
	[LinearRegrReversal],
	[LinearRegressionSlope],
	[Long-term Debt to Capital - Current (LTM)],
	[LongHaulFilter] ,
	[LongLeggedDoji] ,
	[LookUpHighest],
	[LookUpLowest],
	[Low],
	[LowPriceGappingPlay],
	[MACD],
	[MACDHistogram],
	[MACDHistogramCrossover],
	[MACDTwoLines],
	[MACDWithPrices],
	[MAD],
	[MADH],
	[MESASineWave],
	[MF_pct],
	[MajorGannLevels],
	[Mark],
	[Mark %Change],
	[Mark % of underlying value],
	[Mark Change],
	[MarkerIndicator],
	[Market Cap / Common Equity Ratio - Current],
	[MarketForecast],
	[MarketSentiment],
	[Marubozu] ,
	[MassIndex],
	[MatHold] ,
	[MatchingLow] ,
	[McClellanOscillator],
	[McClellanSummationIndex],
	[MedianAverage],
	[MedianPrice],
	[MeetingLines],
	[MiddleHighLowMA],
	[MktFacilitationIdx],
	[ModifiedTrueRange],
	[Momentum],
	[MomentumCrossover] ,
	[MomentumPercent],
	[MomentumPercentDiff],
	[MomentumSMA],
	[MoneyFlow],
	[MoneyFlowIndex],
	[MoneyFlowIndexCrossover],
	[MoneyFlowOscillator],
	[MonkeyBars],
	[MonthlySeasonality],
	[MorningDojiStar],
	[MorningStar],
	[MovAvgAdaptive],
	[MovAvgBandWidth],
	[MovAvgBands],
	[MovAvgEnvelope],
	[MovAvgExpRibbon],
	[MovAvgExponential],
	[MovAvgTriangular],
	[MovAvgTwoLines],
	[MovAvgWeighted],
	[MovingAvgCrossover],
	[MultiCurrencyCorrelationOsc],
	[MyRSIWithNET],
	[NegativeVolumeIndex],
	[Net Chng],
	[Net Income - Current],
	[Net Profit Margin - Current (LTM)],
	[Next3rdFriday],
	[OnBalanceVolume],
	[OnBalanceVolumeModified],
	[OnNeck],
	[OneBlackCrow],
	[OneWhiteSoldier],
	[One_Hundred_SMA_pct_Change],
	[One_Mo_Chg],
	[One_Yr_Chg],
	[OnsetTrendDetector],
	[Open],
	[Open.Int],
	[OpenInterest],
	[Operating Profit Margin - Current (LTM)],
	[OptionDelta],
	[OptionGamma],
	[OptionRho],
	[OptionTheta],
	[OptionVega],
	[P/L Day],
	[P/L Open],
	[P/L %],
	[P/L Year],
	[PE],
	[PMC],
	[PMO],
	[PPS],
	[PairCorrelation],
	[PairRatio],
	[ParabolicSAR],
	[ParabolicSARCrossover],
	[PercentChg],
	[PercentR],
	[PersonsPivots],
	[PiercingLine],
	[PivotPoints],
	[PolarizedFractalEfficiency],
	[PolychromMtm],
	[Net Liq],
	[Pos Qty],
	[PositiveVolumeIndex],
	[Price / Book Value Ratio - Current],
	[Price / Cash Flow Ratio - Current],
	[Price / Earnings Ratio - Current],
	[PriceActionIndicator],
	[PriceAndVolumeTrend],
	[PriceAverageCrossover],
	[PriceChannel],
	[PriceOsc],
	[PriceRatio],
	[PriceTimeFilteringAccVolume],
	[PriceTimeFilteringBarCount],
	[PriceVolumeRank],
	[PriceZoneOscillator],
	[Prob.ITM],
	[Prob.OTM],
	[Prob.Touch],
	[ProjectionBands],
	[ProjectionOscillator],
	[Put Sizzle Index],
	[P/C Ratio],
	[QStick],
	[Quick Ratio - Current (LTM)],
	[RDOC],
	[RSI],
	[RSICrossover],
	[RSIH],
	[RSI_Colorized],
	[RSMK],
	[RS_VA_EMA],
	[RSquared],
	[RainbowAverage],
	[RandomWalkIndex],
	[RangeBands],
	[RangeIndicator],
	[RateOfChange],
	[RateOfChangeCrossover],
	[RateOfChangeWithBands],
	[Ray],
	[RayBearPower],
	[RayBullPower],
	[RecursiveMedianFilter],
	[RecursiveMedianOscillator],
	[Reflex],
	[RegressionDivergence],
	[RelativeMomentumIndex],
	[RelativeRangeIndex],
	[RelativeStrength],
	[RelativeVolatilityIndex],
	[RelativeVolumeStDev],
	[Return on Assets (ROA) - Current (LTM)],
	[ROC],
	[Return on Equity (ROE) - Current (LTM)],
	[ROR],
	[Revenue - Current],
	[ReverseEMA],
	[ReverseEngineeringMACD],
	[ReverseEngineeringRSI],
	[Rho],
	[RibbonStudy],
	[RisingThreeMethods],
	[RocketRSI],
	[STARCBands],
	[SVEPivots],
	[SVEStochRSI],
	[SVEZLRBPercB],
	[Sales Per Share - Current (LTM)],
	[SchaffTrendCycle],
	[SemiCupFormation],
	[SentimentZoneOscillator],
	[SeparatingLines],
	[SequenceCounter],
	[SeriesCount],
	[Shares],
	[ShootingStar],
	[Short Sale Borrowing Rate(%)],
	[SideBySideWhiteLines],
	[SimpleMovingAvg],
	[SimpleTrendChannelFilter],
	[Six_Mo_Chg],
	[Sizzle Index],
	[SlowRSI],
	[SlowVSI],
	[24h/168h Social Activity Ratio],
	[24h/56d Social Activity Ratio],
	[1h/168h Social Activity Ratio],
	[168h/56d Social Activity Ratio],
	[168h_mavg Mentions Count],
	[1d_count Mentions Count],
	[1h_count Mentions Count],
	[SoftAndHardLimiterComparison],
	[Spearman],
	[SpectrumBars],
	[Spreads],
	[StandardDevChannel],
	[StandardDeviation],
	[StandardError],
	[StandardErrorBands],
	[StandardErrorChannel],
	[StickSandwich],
	[Stiffness],
	[StochRSI],
	[StochasticCrossover],
	[StochasticFast],
	[StochasticFull],
	[StochasticFullDiff],
	[StochasticMACD],
	[StochasticMomentumIndex],
	[StochasticSlow],
	[StressIndicator],
	"Strike",
	[SuperPassbandFilter],
	[SwamiAccDist],
	[SwamiConvolution],
	[SwamiIntradayFisher],
	[SwamiIntradayImpulse],
	[SwamiIntradayVolume],
	[SwamiLaguerreTrend],
	[SwamiMarketMode],
	[SwamiPredict],
	[SwamiRelativePerformance],
	[SwamiSwingWave],
	[SwamiVolatility],
	[SwamiVolume],
	[SwingIndex],
	[SymbolRelation],
	[TAC_ADX],
	[TAC_DIMinus],
	[TAC_DIPlus],
	[TEMA],
	[TMV],
	[TPOProfile],
	[TRIX],
	[TTM_LRC],
	[TTM_ScalperAlert],
	[TTM_Squeeze],
	[TTM_Trend],
	[TTM_Wave],
	[Tax Rate - Current (LTM)],
	[TechnicalStockRating],
	[Theo Price],
	[TheoreticalOptionPrice],
	[Theta],
	[ThreeBlackCrows],
	[ThreeInsideDown],
	[ThreeInsideUp],
	[ThreeLineStrike],
	[ThreeOutsideDown],
	[ThreeOutsideUp],
	[ThreeStarsInTheSouth],
	[ThreeWhiteSoldiers],
	[Thrusting],
	[Tick Size],
	[Tick Value],
	[TimeSeriesForecast],
	"Day Close",
	[Total Asset Turnover - Current (LTM)],
	[Total Cost],
	[TradeVolumeIndex],
	[TrendNoiseBalance],
	[TrendPeriods],
	[TrendPersistenceRate],
	[TrendQuality],
	[Trendflex],
	[TriStar],
	[TrueRangeAdjEMA],
	[TrueRangeIndicator],
	[TrueRangeSpecifiedVolume],
	[TrueStrengthIndex],
	[Twenty_Day_Chg],
	[Twenty_SMA_pct_Change],
	[TwoCrows],
	[Two_Hundred_SMA_pct_Change],
	[TypicalPrice],
	[UlcerIndex],
	[UltimateOscillator],
	[Underlying_Last],
	[UndersampledDoubleMovAvg],
	[UniqueThreeRiverBottom],
	[UniversalOscillator],
	[UpsideGapThreeMethods],
	[UpsideGapTwoCrows],
	[UpsideTasukiGap],
	[VPNIndicator],
	[VWAP],
	[VariableMA],
	[Vega],
	[VerticalHorizontalFilter],
	[Vol Diff],
	[Vol Index],
	[VolSizzle],
	[VolatilityStdDev],
	[VolatilitySwitch],
	[Volume],
	[VolumeAccumulation],
	[VolumeAvg],
	[VolumeFlowIndicator],
	[VolumeOsc],
	[VolumeProfile],
	[VolumeRateOfChange],
	[VolumeWeightedMACD],
	[VolumeZoneOscillator],
	[VortexIndicator],
	[VossPredictiveFilter],
	[WarningSymbols],
	[WeaknessInAStrongTrend],
	[WeeklyAndDailyMACD],
	[WeeklyAndDailyPPO],
	[Weighted Back Vol],
	[WeightedClose],
	[WildersSmoothing],
	[WilliamsAD],
	[WilliamsAlligator],
	[WilliamsFractal],
	[WilliamsPercentR],
	[WoodiesPivots],
	[YTD_Chg],
	[YearlyRelativeRange],
	[Close],
	[Yield],
	[ZigZagHighLow],
	[ZigZagPercent],
	[ZigZagSign],
	[ZigZagStepPattern],
	[ZigZagTrendPercent],
	[ZigZagTrendSign],
	[pct_1_Mo_Chg],
	[pct_1_Yr_Chg],
	[pct_20_Day_Chg],
	[pct_5_Day_Chg],
	[pct_6_Mo_Chg],
	[pct_Chg_Open],
	[pct_Chg_from_52Wk_Hi],
	[pct_Chg_from_52Wk_Lo],
	[pct_YTD_Chg]
	)
Go

/****** Object:  Table [dbo].[StocksCANRowBased]    Script Date: 10/14/2024 11:46:10 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[StocksCANRowBased]') AND type in (N'U'))
DROP TABLE [dbo].[StocksCANRowBased]
GO

CREATE TABLE "dbo"."StocksCANRowBased" (
[ID] int NOT NULL IDENTITY(1,1) PRIMARY KEY,
"DATE" date,
[DAYOFWEEK] varchar(50),
[WEEKOFMONTH] varchar(4),
[WEEKOFYEAR] varchar(4),
"Ticker" varchar(20),
"C" varchar(20),
"Name" varchar(max),
"Symbol" varchar(50),
"EPS" decimal(18,4),
"PE" decimal(18,4),
"Yield" decimal(18,4),
"% Chg" decimal(18,4),
"Change" decimal(18,4),
"Price" decimal(18,4),
"Ask" decimal(18,4),
"Bid" decimal(18,4),
"Trd Sz" decimal(18,4),
"Ask Sz" decimal(18,4),
"Bid Sz" decimal(18,4),
"Close" decimal(18,4),
"52 Week Range" decimal(18,4),
"52 High" decimal(18,4),
"High" decimal(18,4),
"Low" decimal(18,4),
"52 Low" decimal(18,4),
"Open" decimal(18,4),
"Call/Put" varchar(20),
"Imp Vol" decimal(18,4),
"Mark" decimal(18,4),
"Exch" varchar(20),
"Mkt Val" decimal(18,4),
"Market Cap" decimal(18,4),
"Shr Os" bigint,
"Volume" integer,
"AVG Volume 6 Month" integer,
"Blk Vol" integer,
"Opn Int" integer,
"Day % P/L" decimal(18,4),
"Day P/L" decimal(18,4),
"% P/L" decimal(18,4),
"P/L" decimal(18,4),
"Book Cost" decimal(18,4),
"Avg Cost" decimal(18,4),
"Entry Date" date,
"Quantity" integer,
"Trade" decimal(18,4),
"Trend" decimal(18,4),
"Opn Int Chg" decimal(18,4),
"Curr" varchar(3),
"Q" varchar(1),
"Div" decimal(18,4),
"Div Pay Dt" date,
"Ex-Div" date,
"Exp Dt" date,
"Num Trd" decimal(18,4),
"Prc Tck" nvarchar(50) COLLATE Latin1_General_100_BIN2,
"Quote Trend" varchar(50),
"Range" decimal(18,4),
"Rel Range" varchar(2),
"Strike" decimal(18,4),
)

USE [StockReporting]
GO

/****** Object:  Table [dbo].[StocksCANRowBased]    Script Date: 10/14/2024 11:46:10 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[StocksCANColumnar]') AND type in (N'U'))
DROP TABLE [dbo].[StocksCANColumnar]
GO

CREATE TABLE "dbo"."StocksCANColumnar" (
[ID] int NOT NULL IDENTITY(1,1) PRIMARY KEY,
"DATE" date,
[DAYOFWEEK] varchar(50),
[WEEKOFMONTH] varchar(4),
[WEEKOFYEAR] varchar(4),
"Ticker" varchar(20),
"C" varchar(20),
"Name" varchar(max),
"Symbol" varchar(50),
"EPS" decimal(18,4),
"PE" decimal(18,4),
"Yield" decimal(18,4),
"% Chg" decimal(18,4),
"Change" decimal(18,4),
"Price" decimal(18,4),
"Ask" decimal(18,4),
"Bid" decimal(18,4),
"Trd Sz" decimal(18,4),
"Ask Sz" decimal(18,4),
"Bid Sz" decimal(18,4),
"Close" decimal(18,4),
"52 Week Range" decimal(18,4),
"52 High" decimal(18,4),
"High" decimal(18,4),
"Low" decimal(18,4),
"52 Low" decimal(18,4),
"Open" decimal(18,4),
"Call/Put" varchar(20),
"Imp Vol" decimal(18,4),
"Mark" decimal(18,4),
"Exch" varchar(20),
"Mkt Val" decimal(18,4),
"Market Cap" decimal(18,4),
"Shr Os" bigint,
"Volume" integer,
"AVG Volume 6 Month" integer,
"Blk Vol" integer,
"Opn Int" integer,
"Day % P/L" decimal(18,4),
"Day P/L" decimal(18,4),
"% P/L" decimal(18,4),
"P/L" decimal(18,4),
"Book Cost" decimal(18,4),
"Avg Cost" decimal(18,4),
"Entry Date" date,
"Quantity" integer,
"Trade" decimal(18,4),
"Trend" decimal(18,4),
"Opn Int Chg" decimal(18,4),
"Curr" varchar(3),
"Q" varchar(1),
"Div" decimal(18,4),
"Div Pay Dt" date,
"Ex-Div" date,
"Exp Dt" date,
"Num Trd" decimal(18,4),
"Prc Tck" nvarchar(50) COLLATE Latin1_General_100_BIN2,
"Quote Trend" varchar(50),
"Range" decimal(18,4),
"Rel Range" varchar(2),
"Strike" decimal(18,4),
)

create NonClustered ColumnStore Index [IX_StocksCANColumnar_ColumnStore] on [StocksCANColumnar]
(
[DAYOFWEEK] ,
[WEEKOFMONTH] ,
[WEEKOFYEAR] ,
"Ticker" ,
"C" ,
"Symbol" ,
"EPS" ,
"PE" ,
"Yield" ,
"% Chg" ,
"Change" ,
"Price" ,
"Ask" ,
"Bid" ,
"Trd Sz" ,
"Ask Sz" ,
"Bid Sz" ,
"Close" ,
"52 Week Range" ,
"52 High" ,
"High" ,
"Low" ,
"52 Low" ,
"Open" ,
"Call/Put" ,
"Imp Vol" ,
"Mark" ,
"Exch" ,
"Mkt Val" ,
"Market Cap" ,
"Shr Os" ,
"Volume" ,
"AVG Volume 6 Month" ,
"Blk Vol" ,
"Opn Int" ,
"Day % P/L" ,
"Day P/L" ,
"% P/L" ,
"P/L" ,
"Book Cost" ,
"Avg Cost" ,
"Entry Date",
"Quantity",
"Trade" ,
"Trend" ,
"Opn Int Chg" ,
"Curr",
"Div" ,
"Div Pay Dt",
"Ex-Div",
"Exp Dt",
"Num Trd",
"Range",
"Strike"
)
Go